version: '3.8'

services:
  golang:
    image: golang:1.24-alpine
    container_name: golang_container
    volumes:
      - ../:/go/src/app
    working_dir: /go/src/app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    tty: true

  redis:
    image: ju1ion/rejson
    ports:
        - "6379:6379"
    volumes:
        - ./redis-data:/data
    environment:
        REDIS_ARGS: "--requirepass redis --user test on >password ~* allcommands --user default off nopass nocommands"
    tty: true
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: